"""
app/postprocessor/tcc_report.py — TCC Report export.

v3.4.0 Sprint 2 — paridade PTW Tutorial §Part 3 p.99-101 (Run > TCC Report).

Reproduce o "TCC Report" do PTW (sortable by Bus Voltage / individual TCC /
all TCCs) com 3 formatadores:

* `format_text` — PTW-style fixed-width
* `format_markdown` — superação visual (tables + headers)
* `format_csv` — datablock-style export (Excel/Pandas compatível)

Reference: PTW Tutorial §Part 3 p.99-101 + §Part 11 p.357-360
(multi-protection plot).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class TccDeviceEntry:
    """A single device line in the TCC report.

    Attributes
    ----------
    device_id
        TAG (e.g. ``"Q1"``, ``"R-50/51-A"``).
    device_type
        ``breaker``, ``fuse``, ``relay``, ``contactor``.
    bus_voltage_kV
        Voltage do bus onde o device está.
    pickup_A
        Corrente de pickup primária.
    time_dial
        Time multiplier setting (TMS).
    curve_type
        IEEE/IEC curve label (e.g. ``"IEC SI"``, ``"ANSI EI"``,
        ``"Class TR"`` for fuse).
    function_code
        ANSI device function (e.g. ``"50/51"``, ``"49"``, ``"87T"``).
    notes
        Free-form text.

    References
    ----------
    PTW Tutorial v8.0 §Part 3 p.99-101 (TCC Report fields).
    """

    device_id: str
    device_type: str = "breaker"
    bus_voltage_kV: float = 0.0
    pickup_A: float = 0.0
    time_dial: float = 0.0
    curve_type: str = ""
    function_code: str = ""
    notes: str = ""


@dataclass
class TccReport:
    """Container for a TCC Report (collection of TccDeviceEntry).

    Reference: PTW Tutorial §Part 3 p.99-101.
    """

    project_name: str
    coordination_zone: str = ""
    devices: list[TccDeviceEntry] = field(default_factory=list)

    def add_device(self, entry: TccDeviceEntry) -> None:
        self.devices.append(entry)

    def sort_by_bus_voltage(self, descending: bool = True) -> None:
        """Sort devices by ``bus_voltage_kV`` (PTW default sort).

        Reference: PTW Tutorial §Part 3 p.99-101.
        """
        self.devices.sort(
            key=lambda d: d.bus_voltage_kV,
            reverse=descending,
        )

    def sort_by_function(self) -> None:
        """Sort by ANSI device function code (e.g. 50/51 < 87T)."""
        self.devices.sort(key=lambda d: d.function_code)

    # -----------------------------------------------------------------
    # Formatters
    # -----------------------------------------------------------------

    def format_text(self) -> str:
        """PTW-style fixed-width text report."""
        lines: list[str] = []
        lines.append("=" * 88)
        lines.append(f" TCC COORDINATION REPORT — {self.project_name}")
        if self.coordination_zone:
            lines.append(f" Zone: {self.coordination_zone}")
        lines.append(" Generated by Olivas Power System Studio")
        lines.append(" Reference: PTW Tutorial §Part 3 p.99-101")
        lines.append("=" * 88)
        lines.append("")
        lines.append(
            f"{'Device':<14} {'Type':<10} {'Bus kV':>8} "
            f"{'Pickup A':>10} {'TMS':>6} {'Curve':<14} {'Func':<8}"
        )
        lines.append("-" * 88)
        for d in self.devices:
            lines.append(
                f"{d.device_id:<14} {d.device_type:<10} "
                f"{d.bus_voltage_kV:>8.3f} "
                f"{d.pickup_A:>10.1f} {d.time_dial:>6.2f} "
                f"{d.curve_type:<14} {d.function_code:<8}"
            )
        lines.append("=" * 88)
        return "\n".join(lines)

    def format_markdown(self) -> str:
        """Markdown — superação visual vs PTW text-only."""
        md: list[str] = []
        md.append(f"# TCC Coordination Report — {self.project_name}")
        if self.coordination_zone:
            md.append("")
            md.append(f"**Zone**: {self.coordination_zone}")
        md.append("")
        md.append("**Reference**: PTW Tutorial §Part 3 p.99-101 + IEEE 242 §15")
        md.append("")
        md.append(
            "| Device | Type | Bus kV | Pickup (A) | TMS | Curve | Func | Notes |"
        )
        md.append(
            "|--------|------|--------|------------|-----|-------|------|-------|"
        )
        for d in self.devices:
            notes = d.notes.replace("|", "\\|") if d.notes else ""
            md.append(
                f"| {d.device_id} | {d.device_type} | "
                f"{d.bus_voltage_kV:.3f} | {d.pickup_A:.1f} | "
                f"{d.time_dial:.2f} | {d.curve_type} | "
                f"{d.function_code} | {notes} |"
            )
        md.append("")
        return "\n".join(md)

    def format_csv(self) -> str:
        """CSV (Excel/Pandas compatible)."""
        lines: list[str] = []
        lines.append(
            "device_id,device_type,bus_voltage_kV,pickup_A,"
            "time_dial,curve_type,function_code,notes"
        )
        for d in self.devices:
            # CSV-safe escape
            notes = d.notes.replace('"', '""') if d.notes else ""
            lines.append(
                f"{d.device_id},{d.device_type},"
                f"{d.bus_voltage_kV:.4f},{d.pickup_A:.2f},"
                f"{d.time_dial:.4f},{d.curve_type},"
                f"{d.function_code},\"{notes}\""
            )
        return "\n".join(lines)


__all__ = [
    "TccDeviceEntry",
    "TccReport",
]
